package inloc;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * The sketch of this class was generated by JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2,
 * based on the InLOC xsd.
 * 
 * @author Florian Jungwirth, Michaela Murauer
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _LOCstructure_QNAME = new QName("http://purl.org/net/inloc/", "LOCstructure");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: test
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LOCstructure }
     * 
     */
    public LOCstructure createLOCstructure() {
        return new LOCstructure();
    }

    /**
     * Create an instance of {@link LOCassociation }
     * 
     */
    public LOCassociation createLOCassociation() {
        return new LOCassociation();
    }

    /**
     * Create an instance of {@link LOCtypeMultilingualToken }
     * 
     */
    public LOCtypeMultilingualToken createLOCtypeMultilingualToken() {
        return new LOCtypeMultilingualToken();
    }

    /**
     * Create an instance of {@link Subject }
     * 
     */
    public Subject createSubject() {
        return new Subject();
    }

    /**
     * Create an instance of {@link LOCtypeMultilingualString }
     * 
     */
    public LOCtypeMultilingualString createLOCtypeMultilingualString() {
        return new LOCtypeMultilingualString();
    }

    /**
     * Create an instance of {@link SchemeObject }
     * 
     */
    public SchemeObject createSchemeObject() {
        return new SchemeObject();
    }

    /**
     * Create an instance of {@link LOCtypeMultilingualStringAnyAttribute }
     * 
     */
    public LOCtypeMultilingualStringAnyAttribute createLOCtypeMultilingualStringAnyAttribute() {
        return new LOCtypeMultilingualStringAnyAttribute();
    }

    /**
     * Create an instance of {@link LOCdefinition }
     * 
     */
    public LOCdefinition createLOCdefinition() {
        return new LOCdefinition();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LOCstructure }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/net/inloc/", name = "LOCstructure")
    public JAXBElement<LOCstructure> createLOCstructure(LOCstructure value) {
        return new JAXBElement<LOCstructure>(_LOCstructure_QNAME, LOCstructure.class, null, value);
    }

}
