/**
 * The sketch of this class was generated by JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2,
 * based on the InLOC xsd.
 * 
 * @author Florian Jungwirth, Michaela Murauer
 */

@javax.xml.bind.annotation.XmlSchema(namespace = "http://purl.org/net/inloc/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package inloc;
